version: "3.10"

networks:
  verim_network:
    name: verim_network
  verim_gateway_network:
    name: verim_gateway_network


services:
  redis:
    image: redis:7.2.0
    container_name: ${CONTAINER_PREFIX}-redis
    networks:
      - verim_network
      - verim_gateway_network
    ports:
      - "13379:6379"
    volumes:
      - verim_redis_data:/var/lib/redis/data/
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: verim-rabbitmq
    container_name: ${CONTAINER_PREFIX}-rabbitmq
    volumes:
      - verim_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - verim_network
      - verim_gateway_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

  gateway:
    container_name: ${CONTAINER_PREFIX}-gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    working_dir: ${DEFAULT_SERVICE_DIR}
    env_file:
      - .env
    volumes:
      # app dir
      - ./gateway/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
    ports:
      - "8000:8000"
    networks:
      - verim_network
      - verim_gateway_network
    restart: unless-stopped

  celery-worker:
    container_name: ${CONTAINER_PREFIX}-celery-worker
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    command: sh -c "celery -A config.celery.app worker -l debug"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      # app dir
      - ./gateway/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
    networks:
      - verim_network
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping --destination celery@$$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  verim_rabbitmq_data:
    name: verim_rabbitmq_data
  verim_redis_data:
    name: verim_redis_data
